import { Injectable, Inject } from '@nestjs/common';
import { randomBytes, randomUUID } from 'crypto';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { hashValue } from '../common/hash/hash.js';
import { REDIS } from '../redis/redis.provider.js';
import { SecretService } from '../secret/secret.service.js';
import type { Redis } from 'ioredis';
import { ClientProxy } from '@nestjs/microservices';
import { EMAIL_SERVICE } from '../broker/broker.module.js';

const OTP_PREFIX = 'otp';

// Redis scripts live as raw Lua files in ./scripts so they can be edited with
// Lua IDE tooling (language server, luacheck, etc.). The Nest CLI copies them
// into dist alongside the compiled output (see nest-cli.json `assets`), so the
// same relative path resolves both in src (tests) and dist (production).
const loadScript = (name: string) =>
  readFileSync(
    fileURLToPath(new URL(`./scripts/${name}`, import.meta.url)),
    'utf8',
  );

export const CREATE_OTP_SCRIPT = loadScript('create-otp.lua');
export const VALIDATE_OTP_SCRIPT = loadScript('validate-otp.lua');

@Injectable()
export class OtpService {
  constructor(
    @Inject(REDIS) private redis: Redis,
    @Inject(EMAIL_SERVICE) private emailClient: ClientProxy,
    private secretService: SecretService,
  ) {}

  private readonly OtpLength = 6;
  private readonly OtpExpiry = 600; // record TTL (seconds)
  private readonly OtpExpiryMinutes = Math.floor(this.OtpExpiry / 60);
  private readonly TimerExpiry = 3600; // generation counter TTL (seconds)
  private readonly OtpHashLen = 16;

  async createOtpRequest(email: string) {
    const otp = this.generateOtp();

    const recordKey = await this.recordKey(email, otp);
    const counterKey = `${OTP_PREFIX}:count:${email}`;

    // Atomic bump-and-store. Older OTPs are implicitly revoked by stamping
    // the new generation onto the record; validation later matches an OTP's
    // generation against the counter.
    await this.redis.eval(
      CREATE_OTP_SCRIPT,
      2,
      counterKey,
      recordKey,
      this.TimerExpiry,
      new Date().toISOString(),
      this.OtpExpiry,
    );

    // Emitted once per request with a stable id the email service uses to
    // suppress duplicate sends on broker redelivery.
    this.emailClient.emit('otp.email', {
      messageId: randomUUID(),
      recipient: email,
      otp: otp,
      subject: 'Your OTP is here',
      expiry: this.OtpExpiryMinutes,
    });

    return;
  }

  /**
   * Validates an OTP against F1.4 and, on success, atomically records its
   * consumption before this method resolves. Returns false for every rejected
   * condition (no match / expired, revoked, already consumed) alike.
   */
  async validateOtp(email: string, otp: string): Promise<boolean> {
    const recordKey = await this.recordKey(email, otp);
    const counterKey = `${OTP_PREFIX}:count:${email}`;

    const result = await this.redis.eval(
      VALIDATE_OTP_SCRIPT,
      2,
      recordKey,
      counterKey,
      new Date().toISOString(),
    );

    // if result is 1, carry on with rest of validation flow
    return result === 1;
  }

  /**
   * Generates and returns a key to store and validate OTPs with
   */
  private async recordKey(email: string, otp: string): Promise<string> {
    const salt = this.secretService.getServerSecret();
    const key = await hashValue(`${email}:${otp}`, salt, this.OtpHashLen);
    return `${OTP_PREFIX}:${key}`;
  }

  /**
   * Generates an OTP using node:crypto library
   */
  generateOtp() {
    const bytes = randomBytes(this.OtpLength);

    // Convert bytes to string using the base64url encoding.
    // This results in a possible character set of [A-Za-z0-9_-]

    // The amount of base64url characters will be more than the generated bytes,
    // hence we slice.
    return bytes.toString('base64url').slice(0, this.OtpLength);
  }
}