import type { Listener, ProcessOutcome } from './types.ts';
import { logger } from '../utils/logger.ts';
import { forgetMessageId, isDuplicate } from './common/dedup.ts';
import { sendEmail } from '../utils/mailer.ts';
import { z } from 'zod';
import {
  MAX_EMAIL_ATTEMPTS,
  OTP_QUEUE,
  RETRY_STEPS,
} from '../utils/topology.ts';
import { renderOtpEmail } from './templates/otp.ts';

export const OtpEmailListener: Listener = {
  queueKey: OTP_QUEUE,
  handler: processOtpEmailMessage,
};

/**
 * Message body routed to the `otp_emails` queue (routing key `otp.email`).
 *
 * Published by user-service's OtpService; validated at the receiving end so a
 * malformed message is nacked instead of reaching the SMTP transport.
 */
const otpEmailMessageSchema = z.object({
  // Stable per-request ID generated by the producer; the consumer uses it to
  // suppress duplicate sends when RabbitMQ redelivers an unacked message.
  messageId: z.uuid(),
  recipient: z.email(),
  otp: z.string().regex(/^[A-Za-z0-9_-]{6}$/),
  subject: z.string().trim().min(1),
  expiry: z.coerce.number().int().positive(),
});

export type OtpEmailMessage = z.infer<typeof otpEmailMessageSchema>;

/** Validate a parsed payload from the `otp_emails` queue (throws on mismatch). */
export function parseOtpEmailMessage(payload: unknown): OtpEmailMessage {
  return otpEmailMessageSchema.parse(payload);
}

/**
 * Parse the raw RabbitMQ body (a JSON-encoded Buffer) and validate it in one
 * step. Throws on malformed JSON or schema mismatch.
 */
export function parseOtpEmailMessageBuffer(body: Buffer): OtpEmailMessage {
  return otpEmailMessageSchema.parse(JSON.parse(body.toString('utf8'))['data']);
}

/**
 * Validate, deduplicate and send one `otp_emails` message. `attempt` is the
 * 1-based delivery attempt, taken from the `x-foc-attempt` header.
 */
export async function processOtpEmailMessage(
  body: Buffer,
  attempt = 1,
): Promise<ProcessOutcome> {
  let data;
  try {
    data = parseOtpEmailMessageBuffer(body);
  } catch (err) {
    logger.error({ err }, 'Invalid otp_emails message');
    return { action: 'dropped' };
  }

  if (await isDuplicate(data.messageId)) {
    return { action: 'acked' };
  }

  const { html, text } = renderOtpEmail({
    otp: data.otp,
    expiresInMinutes: data.expiry,
  });

  try {
    await sendEmail(data.recipient, data.subject, text, html);
    return { action: 'acked' };
  } catch (err) {
    logger.error({ err, attempt }, 'Email send failed');

    // Forget the id so the retried copy of this genuinely-unsent email is not
    // suppressed by the dedup store.
    await forgetMessageId(data.messageId);

    if (attempt < MAX_EMAIL_ATTEMPTS) {
      return {
        action: 'retry',
        delayMs: RETRY_STEPS[attempt - 1].delayMs,
        nextAttempt: attempt + 1,
      };
    }
    return { action: 'dead-letter' };
  }
}
