import type { Listener, ProcessOutcome } from './types.ts';
import { logger } from '../utils/logger.ts';
import { z } from 'zod';
import { forgetMessageId, isDuplicate } from './common/dedup.ts';
import { sendEmail } from '../utils/mailer.ts';
import {
  MAX_EMAIL_ATTEMPTS,
  PASSWORD_RESET_QUEUE,
  RETRY_STEPS,
} from '../utils/topology.ts';
import { renderPasswordResetEmail } from './templates/password-reset.ts';

export const ResetPasswordEmailListener: Listener = {
  queueKey: PASSWORD_RESET_QUEUE,
  handler: processPasswordResetEmailMessage,
};

/**
 * Message body routed to the `password_reset_emails` queue (routing key
 * `password-reset.email`).
 *
 * Published by user-service's PasswordResetService; validated at the receiving
 * end so a malformed message is nacked instead of reaching the SMTP transport.
 */
const passwordResetEmailMessageSchema = z.object({
  // Stable per-request ID generated by the producer; the consumer uses it to
  // suppress duplicate sends when RabbitMQ redelivers an unacked message.
  messageId: z.uuid(),
  recipient: z.email(),
  resetLink: z.url(),
  subject: z.string().trim().min(1),
  expiry: z.coerce.number().int().positive(),
});

export type PasswordResetEmailMessage = z.infer<
  typeof passwordResetEmailMessageSchema
>;

/** Validate a parsed payload from the `password_reset_emails` queue (throws on mismatch). */
export function parsePasswordResetEmailMessage(
  payload: unknown,
): PasswordResetEmailMessage {
  return passwordResetEmailMessageSchema.parse(payload);
}

/**
 * Parse the raw RabbitMQ body (a JSON-encoded Buffer) and validate it in one
 * step. Throws on malformed JSON or schema mismatch.
 */
export function parsePasswordResetEmailMessageBuffer(
  body: Buffer,
): PasswordResetEmailMessage {
  return passwordResetEmailMessageSchema.parse(
    JSON.parse(body.toString('utf8'))['data'],
  );
}

/**
 * Validate, deduplicate and send one `password_reset_emails` message. `attempt`
 * is the 1-based delivery attempt, taken from the `x-foc-attempt` header.
 */
export async function processPasswordResetEmailMessage(
  body: Buffer,
  attempt = 1,
): Promise<ProcessOutcome> {
  let data;
  try {
    data = parsePasswordResetEmailMessageBuffer(body);
  } catch (err) {
    logger.error({ err }, 'Invalid password_reset_emails message');
    return { action: 'dropped' };
  }

  if (await isDuplicate(data.messageId)) {
    return { action: 'acked' };
  }

  const { html, text } = renderPasswordResetEmail({
    resetLink: data.resetLink,
    expiresInMinutes: data.expiry,
  });

  try {
    await sendEmail(data.recipient, data.subject, text, html);
    return { action: 'acked' };
  } catch (err) {
    logger.error({ err, attempt }, 'Email send failed');

    // Forget the id so the retried copy of this genuinely-unsent email is not
    // suppressed by the dedup store.
    await forgetMessageId(data.messageId);

    if (attempt < MAX_EMAIL_ATTEMPTS) {
      return {
        action: 'retry',
        delayMs: RETRY_STEPS[attempt - 1].delayMs,
        nextAttempt: attempt + 1,
      };
    }
    return { action: 'dead-letter' };
  }
}
