services:
  email-service:
    build: .
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS_FILE=${SMTP_PASS_FILE}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_PASSWORD_FILE=${RABBITMQ_PASSWORD_FILE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
    secrets:
      - smtp_password
      - rabbitmq_password_email_service

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - '3050:8080'
      - '25:2525'
secrets:
  smtp_password:
    file: smtp_password.secret
  rabbitmq_password_email_service:
    file: rabbitmq_password.secret
