services:
  user-service:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=${NODE_ENV-development}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
      - DB_PASSWORD_FILE=${DB_PASSWORD_FILE_CLIENT}
      - SERVER_SECRET_FILE=${SERVER_SECRET_FILE}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_PASSWORD_FILE=${RABBITMQ_PASSWORD_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
    secrets:
      - db_password
      - server_secret
      - rabbitmq_password
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
            - dist/
            - test/
            - docs/
            - .env
            - '*.secret'
        - action: rebuild
          path: package.json

  user-db:
    image: postgres:18-alpine
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD_FILE=${DB_PASSWORD_FILE}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - user-db-data:/var/lib/postgresql
    secrets:
      - db_password
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  user-db-data:

secrets:
  db_password:
    file: db_password.secret
  server_secret:
    file: server.secret
  rabbitmq_password:
    file: rabbitmq_password.secret
